all: 
	(cd delaydiff; make all)
	(cd difference; make all)
	(cd differential/deq; make all)
	(cd differential/integrate; make all)

clean: 
	(cd delaydiff; make clean)
	(cd difference; make clean)
	(cd differential/deq; make clean)
	(cd differential/integrate; make clean)

